export const ServiceData = [
    {
        id: 1,
        img: 'https://img3.wallspic.com/crops/2/6/7/8/98762/98762-lagoon-water-palm_tree-arecales-sea-2880x1588.jpg',
        title: "Hotel",
        location: "URL",
        category: "hotel",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 2,
        img: 'https://img3.wallspic.com/crops/2/6/7/8/98762/98762-lagoon-water-palm_tree-arecales-sea-2880x1588.jpg',
        title: "Restaurant",
        location: "URL",
        category: "restaurant",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 3,
        img: "https://d3g2yh83to8qa2.cloudfront.net/wp-content/uploads/sites/16/2016/04/10022027/of-premier-suite_990x590.jpg",
        title: "Hotel",
        location: "AnKara",
        category: "hotel",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 4,
        img: "https://www.picresorts.com/guam/resourcefiles/page-title-image/hotel-pacific-islands-club-guam-tumon-bay.jpg?version=7142022075328",
        title: "Restaurant",
        location: "AnKara",
        category: "restaurant",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 5,
        img: "https://www.picresorts.com/guam/resourcefiles/page-title-image/hotel-pacific-islands-club-guam-tumon-bay.jpg?version=7142022075328",
        title: "Hotel",
        location: "AnKara",
        category: "hotel",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 6,
        img: "https://www.picresorts.com/guam/resourcefiles/page-title-image/hotel-pacific-islands-club-guam-tumon-bay.jpg?version=7142022075328",
        title: "Hotel",
        location: "AnKara",
        category: "hotel",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 7,
        img: "https://www.picresorts.com/guam/resourcefiles/page-title-image/hotel-pacific-islands-club-guam-tumon-bay.jpg?version=7142022075328",
        title: "Restaurant",
        location: "AnKara",
        category: "restaurant",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 8,
        img: "https://www.picresorts.com/guam/resourcefiles/page-title-image/hotel-pacific-islands-club-guam-tumon-bay.jpg?version=7142022075328",
        title: "Restaurant",
        location: "AnKara",
        category: "restaurant",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 9,
        img: "https://www.picresorts.com/guam/resourcefiles/page-title-image/hotel-pacific-islands-club-guam-tumon-bay.jpg?version=7142022075328",
        title: "Hotel",
        location: "AnKara",
        category: "hotel",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 10,
        img: "https://www.picresorts.com/guam/resourcefiles/page-title-image/hotel-pacific-islands-club-guam-tumon-bay.jpg?version=7142022075328",
        title: "Hotel",
        location: "AnKara",
        category: "hotel",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one',
    },
    {
        id: 11,
        img: "https://www.picresorts.com/guam/resourcefiles/page-title-image/hotel-pacific-islands-club-guam-tumon-bay.jpg?version=7142022075328",
        title: "Hotel",
        location: "AnKara",
        category: "hotel",
        price: "3200000",
        description: "With a stay at Seralago Hotel & Suites Main Gate East in Kissimmee, you'll be near the airport, within a 10-minute walk of Fun Spot America and Old Town. Featured amenities include a 24-hour business center, a 24-hour front desk, and multilingual staff. Planning an event in Kissimmee? This aparthotel has 1195 square feet (111 square meters) of space consisting of conference space and a meeting room. Free self parking is available onsite.",
        path: '/service/service-one'
    },
]